image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install dependencies
    command: npm install dotenv morgan cors http express body-parser mongoose  --save
vscode:
  extensions:
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - mgmcdermott.vscode-language-babel@0.0.27:ijOAfHRTZR6L81I11EnYng==
    - vscode-icons-team.vscode-icons@10.1.1:Tp5DMCXZn0uwhjeP1TcmkQ==
    - eamodio.gitlens@10.2.1:e0IYyp0efFqVsrZwsIe8CA==