image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install dependencies
    command: npm install morgan cors http express body-parser mongoose  --save