image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install dependencies
    command: npm install dotenv morgan cors http express body-parser mongoose  --save
vscode:
  extensions:
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
    - joelday.docthis@0.7.1:OOpm9cdbc8T5+PL4o+MM3Q==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==